[feature] 기업 blog website 크롤링 코드 추가
f-lab-edu/llm-mlops pull request #2
Opened 2024-10-19 15:17 UTC by tmdqja75

## 💻 작업 내용

- requests 라이브러리를 사용하여 네이버, 엔씨소프트, Anthropic 블로그 사이트에서 필요한 documents들을 크롤링하는 클래스를 개발했습니다
    - 크롤링된 데이터를 langchain Document형식으로 변환하여 최종적으로 Langchain Document가 담긴 list를 반환합니다.

## ⏩ 앞으로의 과제

- 크롤링된 Langchain Document 내용을 vectorDB에 저장
- 저장된 documents들 RAG 파이프라인에 사용

## 🙋‍♂️ 리뷰 요구사항

- OpenAI 사이트 크롤링은 디버깅 시간이 너무 길어질 것 같아서 일단 코멘트로 보류해놓았습니다! 
- `__main__`으로  테스팅한 코드는 main 브랜치로 merge할때도 포함해서 보내는게 맞을까요?

2024-10-22 15:14 UTC, f-lab-owen requested changes

2024-10-22 15:14 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +)  # 샌드박스 모드를 사용하지 않도록 설정합니다.
`chrome_options` 를 이렇게 전역 변수로 빼두신 이유가 있으실까요?

이보단 `WebsiteDataCrawler`에 클래스 변수나 `statismethod`로 빼면 어떨까요?

2024-10-22 15:14 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +        url = "https://ncsoft.github.io/ncresearch/blogs/"
유지보수를 위해 `url`은 별도 설정(config) 값으로 뺼 수 있는 여지가 있을까요?

2024-10-22 15:14 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +        return filtered_paths
가독성을 위해 이와 같이 수정하면 어떨까요? 의견 부탁드립니다!

```suggestion
        parse_pattern1 = r"^/ncresearch/[a-fA-F0-9]{40}$"
        url = "https://ncsoft.github.io/ncresearch/blogs/"
        site_href_list = self.get_all_hrefs(url)
        pattern = re.compile(parse_pattern)
        filtered_paths = [
            url.replace("/ncresearch/blogs/", "") + path
            for path in site_href_list
            if pattern.match(path)
        ]
        return filtered_paths
```

2024-10-22 15:14 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +    def get_all_hrefs(self, url: str) -> list:
타입형 힌트 작성시 더 구체적으로 작성 부탁드립니다🙏

```suggestion
    def get_all_hrefs(self, url: str) -> list[str]:
```

(이하 다른 함수들도 포함)

2024-10-22 15:14 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +        print(site)
이렇게 모듈을 직접 실행 할 수 있게 구현하셨다면 실행 커맨드와 실행시 어떤 작업을 하는지 주석을 추가해주면 좋습니다.
아래는 예시입니다!

```suggestion
if __name__ == "__main__":
    """ 
    A, B, C를 해서 사이트 목록을 출력
    
    usage: python -m app.data_collection.blog_data
    """        
    website_data = WebsiteDataCrawler()
    site_list = website_data.get_all_docs()

    for site in site_list:
        print(site)
```

2024-10-26 04:18 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +)  # 샌드박스 모드를 사용하지 않도록 설정합니다.
option 변수를 설정하는 부분이라 일단 따로 빼두어놓긴 했어요. 
혹시 클래스 변수롤 사용하는것보다 staticmethod로 사용하게 되면 더 좋은 점이 있을까요?

2024-10-26 04:39 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +        url = "https://ncsoft.github.io/ncresearch/blogs/"
네넵! [2132cce](https://github.com/f-lab-edu/llm-mlops/pull/2/commits/2132ccea4b399fffef8a29d2c007275aec93f876)에 수정해두었습니다!

2024-10-26 04:39 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +    def get_all_hrefs(self, url: str) -> list:
타입 힌트 수정해서 [00d3a3b](https://github.com/f-lab-edu/llm-mlops/pull/2/commits/00d3a3b005cac27ff861a7d66e9bdb053c8181d0)에 올렸습니다!

2024-10-26 04:40 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +        print(site)
[47a2c1f](https://github.com/f-lab-edu/llm-mlops/pull/2/commits/47a2c1fbb6466583d8df056c20f5b8148547c780)에 수정했습니다!

2024-10-26 04:40 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +        return filtered_paths
좀더 깔끔한것 같네요! 이것도 수정해서 올리겠습니다!

2024-10-26 04:46 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +        return filtered_paths
[15b425f](https://github.com/f-lab-edu/llm-mlops/pull/2/commits/15b425fd3735fcf1798b3132b215173952be86b0)에 수정했습니다!

2024-11-03 09:29 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +        url = "https://ncsoft.github.io/ncresearch/blogs/"
dotenv를 활용하시는 걸로 보이는데요. 실행에 필요한 환경변수들을 관리하는 config 파일(예, `.env`)도 해당 PR에 올려주시기 바랍니다. PR은 온전히 실행 할 수 있는 단위가 되어야 해서요!

2024-11-03 09:41 UTC, f-lab-owen commented on app/data_collection/blog_data.py
> +)  # 샌드박스 모드를 사용하지 않도록 설정합니다.
지금과 같은 코드 구현은 상황에 따라 다른 option이 필요한 경우 대응할 수 없습니다.

아래와 같이 클래스 인스턴스 생성시 상황에 맞는 option을 넘겨주거나
```python
def __init__(self, options: Options):
        self.driver = webdriver.Firefox(options=options)
        pass
```

또는 `WebsiteDataCrawler` 에 대한 default 옵션을 넘겨주는 함수를 만들어 재사용하는 것이 적절해 보입니다.

```python
def __init__(self):
        self.driver = webdriver.Firefox(options= WebsiteDataCrawler.get_default_options())

@staticmethod
def get_default_options() -> Options:
	chrome_options = Options()
	chrome_options.add_argument("--headless")  # 브라우저를 헤드리스 모드로 실행합니다.
	chrome_options.add_argument("--disable-gpu")  # GPU를 사용하지 않도록 설정합니다.
	chrome_options.add_argument(
	    "--no-sandbox"
	)  # 샌드박스 모드를 사용하지 않도록 설정합니다.
	return chrome_options
```

"클래스 변수"로 선언/사용은 driver 생성전에 변수가 필요한지라 아래와 같이 구현을 해야할텐데요. 
```
    def __init__(self):
        self.options = ...
        self.driver = webdriver.Firefox(options=chrome_options)
        pass
```
이 경우 역시 staticmethod로 대체가능 해보이기도 하구요.

2024-11-07 11:06 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +)  # 샌드박스 모드를 사용하지 않도록 설정합니다.
옵션들을 크게 바꿀 일은 없을거 같아서 `default_option`으로 넘겨주는게 적절할거 같네요!

2024-11-07 11:12 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +        url = "https://ncsoft.github.io/ncresearch/blogs/"
네넵! [9b20023](https://github.com/f-lab-edu/llm-mlops/pull/2/commits/9b200235e7ff038cf63053b73fd5ddedf49e173a)에 수정했습니다!

2024-11-07 11:13 UTC, tmdqja75 commented on app/data_collection/blog_data.py
> +)  # 샌드박스 모드를 사용하지 않도록 설정합니다.
[97e9045](https://github.com/f-lab-edu/llm-mlops/pull/2/commits/97e9045afd6cb374e578ad2859c7d8576165091f)에 staticmethod로 수정완료했습니다!

2024-11-10 10:42 UTC, f-lab-owen approved these changes
반영해주신 부분들 확인 완료 했습니다 :)

머지시 squashing 머지 해주시기 바랍니다!

<img width="645" alt="image" src="https://github.com/user-attachments/assets/5c02dc01-485c-4fd6-97c0-7fa2842f22fb">

바로 머지하게되면 `master` 브랜치에 모든 커밋 이력이 남게되어 아래와 같은 불편 함이 생깁니다.
- 깔끔한 커밋 내역 유지: 커밋단위를 잘 쪼갰다고 하더라도 단순 머지하게되면 `master`브랜치에 (작업의) 의미단위의 커밋이 아닌 무분별히 많은 커밋들이 쌓이게 됩니다. 이보단 PR을 커밋 하나 단위로 합쳐(squashing) 하여 머지하면 `master` 브랜치에서 작업 내역 추적에 용이합니다
- Revert 용이함: 코드 리뷰 및 반영은 PR단위로 하게 되는데요. 머지된 코드에 대해 롤백을 하고자 하는 경우, squashing하여 하나의 커밋으로 처리된 경우 손쉽게 롤백을 할 수 있습니다.

이 외에도 "코드 리뷰 및 디버깅에서의 이점", "브랜치 관리 간소화", "협업 시 혼란 방지" 등을 위해 머지시 스쿼싱 하는걸 권장 드립니다.

2024-11-13 11:49 UTC, merged