[feature] vectorstore hybrid search 기능 추가
f-lab-edu/llm-mlops pull request #3
Opened 2024-10-20 13:35 UTC by tmdqja75

## 💻 작업 내용

- Opensearch Vectorstore docker compose 파일 작성
- Vectorstore에서 쿼리 관련 documents들을 hybrid search로 retrieve하는 코드 작성

## ⏩ 앞으로의 과제

- RAG Pipeline에 Opensearch Vectorstore Retriever 추가

## 🙋‍♂️ 리뷰 요구사항

- _reciprocal_rank_fusion 메서드에서 `df.apply()`에서 사용할 임시 함수 (`def ref_score()`)를 메서드 안에 넣어서 작성했는데, 이런 임시 함수는 클래스 밖으로 따로 빼는게 나을지 궁금합니다!

2024-10-22 15:46 UTC, f-lab-owen requested changes

2024-10-22 15:46 UTC, f-lab-owen commented on pyproject.toml
> +[tool.poetry]
해당 파일의 changes는 https://github.com/f-lab-edu/llm-mlops/pull/1  머지되면 살펴보도록 할게요~!

(참고. https://github.com/f-lab-edu/llm-mlops/pull/1 머지되면 from `main` to `feature/vectorstore` 최신 코드 땡겨와 머지하신 후 `feature/vectorstore` 재차 푸시 해주세요)

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/docker-compose.yaml
> +      - bootstrap.memory_lock=true # JVM 힙 메모리 스와핑 비활성화
해당 옵션을 활성화 하신 이유가 따로 있으실까요?

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/docker-compose.yaml
> +        hard: -1
실배포에 앞서 작업하시는 머신에 적절한 리소스로 할당해 두는걸 권장 드립니다.
이후 추가적인 배포작업 PR로 또 적절히 리소스 조정하는 작업이 필요하구요

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +load_dotenv(override=True)
여기서 `load_dotenv(override=True)`를 하신 이유가 있으실까요?

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +    ):
해당 모듈 외부에서 `OPENSEARCH_PW`에 접근이 가능하기 때문에 보안상 취약합니다! 
더불어,  클래스 생성자 param 중 `user`, `pw`에 대해 default 값이 할당되어야 하는 이유가 있을까요?

`OpenSearchHybridSearch` 클래스 인스턴스를 생성하는 코드에서 값을 넘기도록 하고, default값은 제외시키는게 맞아 보입니다.

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        )
HuggingFaceHub에서 임베딩 모델을 가져오는데 시간이 오래 거릴 수 있습니다!
기본적인 사항들을 체크하고 최대한 마지막에 로드하는 방식이 오류 발생시 확인에 소요되는 시간이 적을 것 같습니다.

```suggestion
        # OpenSearch HTTP 인증 정보 설정
        self.opensearch_http_auth = (user, pw)
        # OpenSearch 클라이언트 초기화
        self.client = OpenSearch(
            hosts=[{"host": host, "port": port}],
            http_auth=self.opensearch_http_auth,
            use_ssl=True,
            verify_certs=False,
            connection_class=RequestsHttpConnection,
        )
        # OpenSearch URL 구성
        self.openserach_url = f"https://{host}:{port}"
        
        
        # HuggingFace를 사용하여 임베딩 모델 설정
        self.embeddings = HuggingFaceEmbeddings(model_name=HUGGINGFACE_EMBEDDING_MODEL)

        # OpenSearch 벡터 스토어 초기화
        self.vector_store = OpenSearchVectorSearch(
            index_name=OPENSEARCH_BLOG_DATA_INDEX,
            embedding_function=self.embeddings,
            opensearch_url=self.openserach_url,
            http_auth=self.opensearch_http_auth,
            use_ssl=True,
            verify_certs=False,
            ssl_show_warn=False,
        )
```

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        """Reciprocal Rank Fusion 알고리즘을 사용하여 결과를 결합합니다.
해당 알고리즘에 대한 설명이나 관련 참조 링크가 있으면 좋겠습니다!

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            )
BM25, cosine_similarty를 계산하는 로직은 별도 함수 또는 util 모듈 하위로 옮긴 다음 가져다 쓰면 어떨까요?

지금 구현상으론 hybrid search만 지원하는데, BM25 결과만 또는 cosin_similarity 결과만 보고 싶은 경우도 있을 것 같고, 이를 지원하기 위해선 `bm25`, `cosine_similarty`(또는 `semantic_search`) 함수를 만들고 각각의 로직을 결국 다시 써야 해서요.

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            result (dict): 검색 결과 데이터.
`dict` 와 같은 구조체 param에 대해선 좀 더 구체적으로 설명해주면 좋습니다

예를 들어 아래와 같이요~!
```
- K: `_source` , V: ...
   -  K: `metadata`, V: 메타데이터
```

지금 코드상으론 해당 함수에서 작동하는 로직을 다루는데 핵심인 `result` parameter의 argument값에 대해 코드만으론 파악이 힘듭니다.

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            pd.DataFrame: 파싱된 결과의 데이터프레임.
`dataFrame` 역시 좀더 자세한 설명이 있어야 해당 함수로부터 결과를 반환 받아 사용하는데 용이 할 것 같습니다.

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        self.vector_store.add_documents(doc_list)
logger를 추가해보면 좋을 것 같네요?! bulk insert라서 요청하는 문서 삽입 사이즈에 따라 소요되는 시간이 달라질텐데요.
logger를 추가해서 진행 상황을 알려주면 좋을 것 같습니다.

지금과 같은 상황이면, 삽입되는 문서 사이즈가 큰경우 콘솔 또는 로그창에서 아무 메시지 없이 멈춰있는 것으로 인지될 수 있어요
```suggestion
    def insert_docs(self, doc_list: List[Document]) -> None:
        """문서를 인덱스에 삽입합니다.

        Args:
            doc_list (List[Document]): 삽입할 문서 목록.
        """
        # 문서를 벡터 스토어에 삽입
        logging.info(f"Inserting {len(doc_list}) document(s)...") 
        self.vector_store.add_documents(doc_list)
        logging.info(f"Done {len(doc_list}) document(s) insertion") 
```

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            "size": top_k * 2,
top_k 보다 두배로 검색하는 이유가 무엇인가요?

2024-10-22 15:46 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        )
첫번째 검색 요청이 끝나기 전까진 두번째 요청이 시작되지 않아 소요시간이 오래 걸리는 구현 방식 입니다!
이를 동시에 처리 할 수 있도록 수정이 필요해보여요~!

더불어서 `hybrid_search` 뿐만 아니라, 각각 `bm25_search`, `cosine_similarity_search` 에서도 사용 될 수 있는 구현 내용이라 코드 분리가 필요해 보입니다! (검색 결과 파싱도 동일)

2024-11-08 10:02 UTC, tmdqja75 commented on app/vectorstore/docker-compose.yaml
> +      - bootstrap.memory_lock=true # JVM 힙 메모리 스와핑 비활성화
[Opensearch 공식 doc](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml)에서 사용한 config를 참조해서 `docker-compose.yaml`작성 했었어요! 환경변수를 제거하면 혹시라도 에러 날까봐 doc에서 사용한 config 그대로 놔두었어요

2024-11-08 10:04 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +load_dotenv(override=True)
아 디버깅하면서 쓴 인자가 그대로 올라가벼렸네요 ㅜㅜ 메인 코드로 돌릴땐 필요하진 않습니다!

2024-11-08 10:09 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +    ):
아하 네넵! 그럼 보안을 위해서 user, pw는 인자로 받는것으로 수정해겠습니다!

2024-11-08 10:14 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +    ):
[aeb5b08](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/aeb5b08d97055f23a9795c86f352c517686267dd)에 수정했습니다!

2024-11-08 10:18 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +        )
[9af4741](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/9af474142c99526736b5660477ea2d20b623a279)에 수정했습니다!

2024-11-08 10:22 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +        """Reciprocal Rank Fusion 알고리즘을 사용하여 결과를 결합합니다.
[88a4e71](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/88a4e71c1642381664c6c7f54979a3e0e15c05f7)에 추가했습니다!

2024-11-08 11:32 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            )
그럼 클래스에 `hybrid_search` 메서드만 제공하지 않고 아래처럼 bm25랑 cosine메서드도 제공하는게 좋겠네요!

```python
class OpenSearchHybridSearch:
    ...
    def hybrid_search():
        ....
        return result
    def bm25():
        ....
        return result
    def cosine_similarity():
        ....
        return result
```

2024-11-08 12:06 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            result (dict): 검색 결과 데이터.
함수가 맨 아래같이 OpenSearch 데이터베이스 전체 결과를 input으로 받는데 docstring에 꼭 필요한 정보만 정보만 적어도 될까요?
```python
"""
- hits (dict): ...
    - hits (list): ...
    - _source
    - 
"""
```
 아니면 dict 전체 인자 정보를 적을 필요가 있을까요?


```json
{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "my_index",
                "_type": "_doc",
                "_id": "1",
                "_score": 1.0,
                "_source": {
                    "title": "First Document",
                    "content": "This is the content of the first document.",
                    "timestamp": "2024-10-01T12:34:56",
                    "tags": ["example", "test"],
                    "views": 100
                }
            },
            {
                "_index": "my_index",
                "_type": "_doc",
                "_id": "2",
                "_score": 0.8,
                "_source": {
                    "title": "Second Document",
                    "content": "This is the content of the second document.",
                    "timestamp": "2024-10-02T14:22:01",
                    "tags": ["sample", "open"],
                    "views": 150
                }
            }
        ]
    }
}
```

2024-11-08 12:13 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            pd.DataFrame: 파싱된 결과의 데이터프레임.
[42ae615](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/42ae615a7c95d5fb325e65b75bade99ec840cef4)에 수정했습니다!

2024-11-08 12:25 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            "size": top_k * 2,
hybridsearch에서 쿼리되는 doc들을 좀 더 다양하게 하려고 각각 두배로 검색한 후 RRF로 re-ranking한 뒤 top-k만큼만 결과를 반환하려 했습니다!
혹시 딱 top_k만큼만 쿼라히는게 더 효율적일까요?

2024-11-08 12:32 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +        self.vector_store.add_documents(doc_list)
[e3f35ae](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/e3f35aec6ba6a02e25147b3270e01938c20e4ea3)에 로깅하는 부분 추가했습니다!
간단한 에러 핸들링 부분도 추가했습니다!

2024-11-08 12:36 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +        )
동시 처리하는 방법 한번 고민해보겠습니다! 
아예 opensearch db 쿼리단에서 한번에 hybrid search하는 쿼리를 써서 하는것도 방법일까요?

2024-11-14 11:13 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +load_dotenv(override=True)
그렇다면 제거 부탁드립니다 🙏

2024-11-14 11:15 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            "size": top_k * 2,
코드 수정 요청보다는 이렇게 구현하신 의도가 궁금하여 드린 질문입니다! :)
해당 값(`* 2`)도 검색결과 품질에 영향을 끼칠 수 있으니 `hybrid_search(...)` 함수의 argument로 추가하면 어떨까요?

2024-11-14 11:19 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        )
opensearch 자체에서도 hybrid search를 할 순 있습니다. ([참고](https://opensearch.org/docs/latest/search-plugins/hybrid-search/)) 해당 부분 살펴보시고 적용가능 하다면 반영해주시기 바랍니다!

2024-11-14 11:21 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            logging.warning(f"Error during document insertion!")
해당 함수를 호출하고 나서 인덱스에 문서가 정상적으로 추가되었는지 판단 할 수 없을 것 같습니다.
정상적으로 처리됐음을 True/False로 반환해주면 어떨까요?

2024-11-14 11:25 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        self.vector_store.add_documents(doc_list)
문서 삽입에 실패하는 경우가 고려되어야 합니다.  `self.vector_store.add_documents` 함수에서 성공/실패 정보를 반환하고, 삽입 결과를 토대로 실패시 어떠한 행동을 할지 고민해주시기 바래요

2024-11-14 11:26 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            result (dict): 검색 결과 데이터.
전체 정보는 불필요하고 실제로 도움이 되진 않을 것 같습니다. 코드를 보는 사람의 입장에서 해당 함수를 사용하는데 있어 필요한 정보가 무엇인지 생각해보고 docstring에 추가해주세요!

2024-11-14 11:27 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +            )
얘기주신 것처럼 `hybrid_search`, `bm25`, `cosine_similarity`로 함수화 진행해 주세요!
그리고 각 함수가 `OpenSearchHybridSearch` 의 멤버변수을 활용하진 않을 것 같은데요. 그래서 클래스 함수보단 유틸성 함수로 생각됩니다. `utils.py` 또는 `ops.py` 와 같은 유틸성 모듈을 추가하고 각 함수를 추가하면 재사용 측면에서도 좋을 것 같습니다.

2024-11-14 15:26 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        )
비동기처리로도 할 수 있을 것 같고, 관련해선 [#](https://docs.bentoml.com/en/latest/guides/services.html#convert-synchronous-to-asynchronous)에서 인사이트를 얻을 수 있을 것 같습니다.

다만 비동기 방식을 지원하려면 함수를 처음 호출하는 부분부터해서 최종 로직가지 모두 비동기화가 필요하기에 비동기에 대한 깊은 이해가 없다면 완벽한 비동기처리 구현은 힘들 수 있는 점 참고해주세요~!

```
# async scope에서
foo = await foo_fn(...)

async foo_fn(...):
     return await bar_fn(...)

async bar_fn(...):
    result = long_time_processing_fn(...)  # <- 해당 함수가 오래 걸리는 작업인데 비동기화 안되어 있으므로 결국 이부분이 병목으로 작용하여 온전한 비동기 프로세스가 되지 않음
    return result
```

2024-11-29 06:38 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            result (dict): 검색 결과 데이터.
[25063e2](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/25063e251ae5bfd9465e9392c46e32cfed603136)에 doctoring 수정했습니다!

2024-11-29 06:39 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +load_dotenv(override=True)
[f2d4e48](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/f2d4e482da3542450a3f6e472619740c132744d4) 수정완료했습니다!

2024-11-29 06:44 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            )
[9c733d6](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/9c733d6dc5364e186ca6c89856a27641b328d03c)에 bm25, cosine_similairty 서치 기능 추가했습니다! 클래스 내부에 있는 OpenSearch 클라이언트 멤버 변수 (`self.client`)를 활용하여 위해 `OpenSearchHybridSearch`클래스 내부 메서드로 기능 생성했습니다!

2024-11-29 07:18 UTC, tmdqja75 commented on app/vectorstore/opensearch_hybrid.py
> +            logging.warning(f"Error during document insertion!")
[3ec3141](https://github.com/f-lab-edu/llm-mlops/pull/3/commits/3ec3141bb2273d2c5844142ba53354f00d8faa96)에 수정했습니다!

2024-11-29 13:02 UTC, f-lab-owen commented on app/vectorstore/opensearch_hybrid.py
> +        )
별도 PR로 진행하기로 했습니다!

2024-12-02 08:43 UTC, f-lab-owen approved these changes
> 문서 삽입에 실패하는 경우가 고려되어야 합니다.  self.vector_store.add_documents 함수에서 성공/실패 정보를 반환하고, 삽입 결과를 토대로 실패시 어떠한 행동을 할지 고민해주시기 바래요

위 코멘트는 선택 반영인 부분이라 일단 어푸로브 하였습니다~!

2024-12-02 23:38 UTC, merged