[feature] langgraph tools (websearch, vectorstore search) 생성
f-lab-edu/llm-mlops pull request #6
Opened 2024-12-03 14:35 UTC by tmdqja75

## 💻 작업 내용

- langgraph에서 사용할 langchain tools 생성

## ⏩ 앞으로의 과제

- LangGraph와 tools 연동

## 🙋‍♂️ 리뷰 요구사항

- `app/` 디렉토리에 있는 `vectorstore` 커스텀 패키지가 import가 안되서 `sys.path`에 임의로 parent path를 추가하여 해결했는데 좀 더 나은 솔루션이 있는지 궁금합니다!

2024-12-04 08:59 UTC, f-lab-owen commented
> app/ 디렉토리에 있는 vectorstore 커스텀 패키지가 import가 안되서 sys.path에 임의로 parent path를 추가하여 해결했는데 좀 더 나은 솔루션이 있는지 궁금합니다!

구현하신 tools.py 를 가져다 쓰는 곳이 어떻게 되죠? 가져다 쓰는 곳 또는 실행하는 지점에 따라서 방법이 달라질 것 같습니다.
(내일 멘토링 시간에 같이 코드보면서 얘기 나눠보도록 해요 :)

2024-12-07 13:22 UTC, f-lab-owen requested changes

2024-12-07 13:22 UTC, f-lab-owen commented on app/langgraph/tools.py
> +import sys
사용하지 않는 패키지입니다. 삭제 해주세요~!

2024-12-07 13:22 UTC, f-lab-owen commented on app/langgraph/tools.py
> +    """search OpenSearch vector databsee for documents that are relevant to a given query
오타가 있습니다
```suggestion
    """search OpenSearch vector database for documents that are relevant to a given query
```

2024-12-08 06:58 UTC, tmdqja75 commented on app/langgraph/tools.py
> +    """search OpenSearch vector databsee for documents that are relevant to a given query
[165f27d](https://github.com/f-lab-edu/llm-mlops/pull/6/commits/165f27dc6a00e64fbb3f3bed2905f6b556a38fb5)에 미사용 import + 오타 수정했습니다!

2024-12-08 09:03 UTC, f-lab-owen approved these changes

2024-12-08 13:34 UTC, merged