[fix] BentoML LLM 서버에 Langraph 추가
f-lab-edu/llm-mlops pull request #7
Opened 2024-12-13 09:58 UTC by tmdqja75

## 💻 작업 내용

- BentoML에 LangGraph 기능 추가
    - user query가 주제와 연관 있는지 확인하는 분기처리 추가
- OpenAI 모델 사용 옵션 추가

## ⏩ 앞으로의 과제
- LangGraph nodes/edges 추가 예정

## 🙋‍♂️ 리뷰 요구사항
- 이번 PR은 없습니다!

2024-12-14 07:12 UTC, f-lab-owen requested changes

2024-12-14 07:12 UTC, f-lab-owen commented on app/llm_server/graph.py
> +        If the query contains keyword(s) or semantic meaning related to the give topics, grade it as relevant. \n
오탈자입니다!

```suggestion
        If the query contains keyword(s) or semantic meaning related to the given topics, grade it as relevant. \n
```

2024-12-14 07:12 UTC, f-lab-owen commented on app/llm_server/graph.py
> +        Respond in JSON with `is_relavant` key.
`is_related` key가 맞지 않을까요?

또는 코드 전반에 `is_related`와 `is_relevant`가 혼용되어있어서 맞추면 좋겠습니다

```suggestion
        Respond in JSON with `is_related` key.
```

2024-12-14 07:12 UTC, f-lab-owen commented on app/llm_server/graph.py
> +from utils.env_setup import get_device
사용되지 않는 패키지가 import 되어 있습니다!

2024-12-14 07:12 UTC, f-lab-owen commented on app/llm_server/utils/env_setup.py
> +
불필요한 줄바꿈이 있습니다. (black-formatter로 사전에 검토 가능!)

2024-12-16 23:35 UTC, tmdqja75 commented on app/llm_server/utils/env_setup.py
> +
[1e7c690](https://github.com/f-lab-edu/llm-mlops/pull/7/commits/1e7c690aee9d2d6e1b1571c027e25b3d1c9b802e)에 오탈자, formatting, import 수정했습니다!

2024-12-18 09:40 UTC, f-lab-owen approved these changes
수고하셨습니다👍

2024-12-22 09:02 UTC, merged